version: "2.0"

services:
  
  tnpp-proxy:
    image: "lingsoft/tnpp-proxy:1.0.0-elg"
    environment: []
    restart: always

  restserver:
    image: registry.gitlab.com/european-language-grid/ilsp/elg-lt-service-execution-all:production-reactive
    command:
    - "--spring.webflux.base-path=/execution"
    - "--logging.level.elg.ltserviceexecution.api=WARN"
    - "--elg.ltservices.staticServices.tnpp-proxy=http://tnpp-proxy:8000/process"
    - "--elg.base.url=http://localhost:5080/execution"
    restart: always

  try_gitlab_com_european_language_grid_cuni_gui_udpipe_latest:
    image: "registry.gitlab.com/european-language-grid/cuni/gui-udpipe:latest"
    restart: always

  i18n:
    image: registry.gitlab.com/european-language-grid/platform/i18n-service:latest
    restart: always

  frontend:
    image: "nginx:alpine"
    ports:
    - "5080:80"
    volumes:
    - ./nginx-conf:/etc/nginx/templates
    restart: always
